### ISSUE TITLE
有考虑过加入代理功能么

### ISSUE THREAD

**Issue by ccqgithub** [fex-team/fis3-command-server#3]
https://github.com/nodejitsu/node-http-proxy 
比如前端调用接口的项目中，所有的数据通过接口开发，如果有代理功能，可以将ajax请求全部转发到接口服务器。。现在是通过nginx配置的

**Comment by 2betop** [comment]
应该现在就支持。

fis.baidu.com/fis3/docs/node-mock.html

**Comment by ccqgithub** [comment]
好的，我试一下~

**Comment by ccqgithub** [comment]
好像目前代理支持还不是很好，我现在用在server目录下添加自定义`server.js`的方式…… 🐈

**Comment by 2betop** [comment]
主要是哪些功能欠缺可以在这说说，后续可以考虑加上

**Comment by ccqgithub** [comment]
具体功能不清楚，，只不过在server.conf里配置
`proxy ^\/api\/(.+) http://www.api.com/api/$1`  很久没有调通。。就直接用server.js 了, 通过fis-server-node 修改的。。

```
var proxy = require('http-proxy-middleware');
// add proxy support
var apiAddress = 'http://app.dev.nakedhub.cn';
app.use('/api', proxy({
  target: apiAddress,
  changeOrigin: true,
  pathRewrite: {
    '^/api': '/nakedhub'
  },
}));
```
